name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_coding:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to coding'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@e.coding.net:akilar/akilar/tool.git
          ssh_private_key:
            ${{ secrets.ID_RSA }}
